### ISSUE TITLE
How about new post about pirating some commonly use software?

### ISSUE THREAD

**Issue by t0nychan** [maximousblk/raven#2]
For example, Microsoft Windows, Microsoft office, Adobe CC

**Comment by maximousblk** [comment]
This blog heavily based on r/piracy so posts labled "guide" are totally legible here. Make sure it is updated and properly credited

**Comment by maximousblk** [comment]
Added piracy 101
@t0nychan  https://maximousblk.github.io/raven/2020-01-31-piracy-101/
